version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_dev
    environment:
      SA_PASSWORD: "MinhaSenha123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_dev
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_dev
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  sqlserver_data: