CREATE DATABASE OrcamentoMedico;
GO

USE OrcamentoMedico;
GO

CREATE TABLE Usuarios (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    SenhaHash VARCHAR(255) NOT NULL,
    CriadoEm DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET()
);
GO

CREATE TABLE Atendentes (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdUsuario UNIQUEIDENTIFIER NOT NULL,
    CriadoEm DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    FOREIGN KEY (IdUsuario) REFERENCES Usuarios(Id)
);
GO

CREATE TABLE Pedidos (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IdUsuario UNIQUEIDENTIFIER NOT NULL,
    CriadoEm DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    Status VARCHAR(50) NOT NULL DEFAULT 'PENDENTE',
    ImagemS3 VARCHAR(MAX) NOT NULL,
    EmAtendimento BIT NOT NULL DEFAULT 0,
    FOREIGN KEY (IdUsuario) REFERENCES Usuarios(Id) ON DELETE CASCADE
);
GO

CREATE TABLE Orcamentos (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PedidoId UNIQUEIDENTIFIER,
    AtendenteId UNIQUEIDENTIFIER,
    Valor DECIMAL(10,2) NOT NULL,
    PrazoDias INT NOT NULL,
    Aprovado BIT NOT NULL DEFAULT 0,
    CriadoEm DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    FOREIGN KEY (PedidoId) REFERENCES Pedidos(Id) ON DELETE CASCADE,
    FOREIGN KEY (AtendenteId) REFERENCES Atendentes(Id) ON DELETE SET NULL
);
GO